name: CI tests for CLN watchtower-plugin

on: [push, pull_request]

jobs:
  cache-cln:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Create CLN cache
        id: cache-cln
        uses: actions/cache@v3
        env:
          cache-name: cache-cln-dev
        with:
          path: lightning
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.11.0.1 
      - name: Install CLN
        if: ${{ steps.cache-cln.outputs.cache-hit == 'false' }}
        run: |
          sudo apt-get update && sudo apt-get install gettext
          git clone https://github.com/ElementsProject/lightning.git && cd lightning && git checkout v0.11.0.1
          pip install --user poetry && poetry install && source $(poetry env info -p)/bin/activate
          ./configure --enable-developer
          make && sudo make install

  cln-plugin:
    needs: cache-cln
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install bitcoind (0.20.1)
        run: |
          wget https://bitcoincore.org/bin/bitcoin-core-0.20.1/bitcoin-0.20.1-x86_64-linux-gnu.tar.gz
          tar -xzf bitcoin-0.20.1-x86_64-linux-gnu.tar.gz
          ln -s $(pwd)/bitcoin-0.20.1/bin/bitcoind /usr/local/bin
          ln -s $(pwd)/bitcoin-0.20.1/bin/bitcoin-cli /usr/local/bin
      - name: Load CLN cache
        id: cache-cln
        uses: actions/cache@v3
        env:
          cache-name: cache-cln-dev
        with:
          path: lightning
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.11.0.1 
      - name: Link CLN
        run: |
          cd lightning && sudo make install
      - name: Install teos and the plugin
        run: |
          cargo install --path teos 
          cargo install --path watchtower-plugin
      - name: Add test dependencies
        run: |
          cd watchtower-plugin/tests
          pip install --user poetry && poetry install
      - name: Run tests
        run: |
          cd watchtower-plugin/tests
          source $(poetry env info -p)/bin/activate
          DEVELOPER=1 pytest test.py